name: Publish release
on:
  release:
    types: [published]
permissions:
  contents: write
  id-token: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build the `pdfjs-dist` library
        run: npx gulp dist

      # Rubicon Fork start
      - name: action-zip
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r build_${{github.event.release.tag_name}}.zip ./build

      - name: publish to release page
        uses: softprops/action-gh-release@v2
        with:
          files: build_${{github.event.release.tag_name}}.zip
      # Rubicon Fork end
